/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ExecuteSourceDiscoverSchemaResponse {
    
    public String contentType;

    public ExecuteSourceDiscoverSchemaResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Input failed validation
     */
    
    public WayScript.airbyte_test.models.shared.InvalidInputExceptionInfo invalidInputExceptionInfo;

    public ExecuteSourceDiscoverSchemaResponse withInvalidInputExceptionInfo(WayScript.airbyte_test.models.shared.InvalidInputExceptionInfo invalidInputExceptionInfo) {
        this.invalidInputExceptionInfo = invalidInputExceptionInfo;
        return this;
    }
    
    /**
     * Successful operation
     */
    
    public WayScript.airbyte_test.models.shared.SourceDiscoverSchemaRead sourceDiscoverSchemaRead;

    public ExecuteSourceDiscoverSchemaResponse withSourceDiscoverSchemaRead(WayScript.airbyte_test.models.shared.SourceDiscoverSchemaRead sourceDiscoverSchemaRead) {
        this.sourceDiscoverSchemaRead = sourceDiscoverSchemaRead;
        return this;
    }
    
    
    public Integer statusCode;

    public ExecuteSourceDiscoverSchemaResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ExecuteSourceDiscoverSchemaResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ExecuteSourceDiscoverSchemaResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
