/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOpenApiSpecResponse {
    
    public String contentType;

    public GetOpenApiSpecResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOpenApiSpecResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOpenApiSpecResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Returns the openapi specification file
     */
    
    public byte[] getOpenApiSpec200TextPlainBinaryString;

    public GetOpenApiSpecResponse withGetOpenApiSpec200TextPlainBinaryString(byte[] getOpenApiSpec200TextPlainBinaryString) {
        this.getOpenApiSpec200TextPlainBinaryString = getOpenApiSpec200TextPlainBinaryString;
        return this;
    }
    
    public GetOpenApiSpecResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
