/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListDestinationDefinitionsResponse {
    
    public String contentType;

    public ListDestinationDefinitionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful operation
     */
    
    public WayScript.airbyte_test.models.shared.DestinationDefinitionReadList destinationDefinitionReadList;

    public ListDestinationDefinitionsResponse withDestinationDefinitionReadList(WayScript.airbyte_test.models.shared.DestinationDefinitionReadList destinationDefinitionReadList) {
        this.destinationDefinitionReadList = destinationDefinitionReadList;
        return this;
    }
    
    
    public Integer statusCode;

    public ListDestinationDefinitionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListDestinationDefinitionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListDestinationDefinitionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
