/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListPrivateDestinationDefinitionsResponse {
    
    public String contentType;

    public ListPrivateDestinationDefinitionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful operation
     */
    
    public WayScript.airbyte_test.models.shared.PrivateDestinationDefinitionReadList privateDestinationDefinitionReadList;

    public ListPrivateDestinationDefinitionsResponse withPrivateDestinationDefinitionReadList(WayScript.airbyte_test.models.shared.PrivateDestinationDefinitionReadList privateDestinationDefinitionReadList) {
        this.privateDestinationDefinitionReadList = privateDestinationDefinitionReadList;
        return this;
    }
    
    
    public Integer statusCode;

    public ListPrivateDestinationDefinitionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListPrivateDestinationDefinitionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListPrivateDestinationDefinitionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
