/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListLatestSourceDefinitionsResponse {
    
    public String contentType;

    public ListLatestSourceDefinitionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful operation
     */
    
    public WayScript.airbyte_test.models.shared.SourceDefinitionReadList sourceDefinitionReadList;

    public ListLatestSourceDefinitionsResponse withSourceDefinitionReadList(WayScript.airbyte_test.models.shared.SourceDefinitionReadList sourceDefinitionReadList) {
        this.sourceDefinitionReadList = sourceDefinitionReadList;
        return this;
    }
    
    
    public Integer statusCode;

    public ListLatestSourceDefinitionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListLatestSourceDefinitionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListLatestSourceDefinitionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
