/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class SaveSyncConfigResponse {
    
    public String contentType;

    public SaveSyncConfigResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful Operation
     */
    
    public WayScript.airbyte_test.models.shared.InternalOperationResult internalOperationResult;

    public SaveSyncConfigResponse withInternalOperationResult(WayScript.airbyte_test.models.shared.InternalOperationResult internalOperationResult) {
        this.internalOperationResult = internalOperationResult;
        return this;
    }
    
    
    public Integer statusCode;

    public SaveSyncConfigResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public SaveSyncConfigResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public SaveSyncConfigResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
