/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class WebBackendListGeographiesResponse {
    
    public String contentType;

    public WebBackendListGeographiesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public WebBackendListGeographiesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public WebBackendListGeographiesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Successful operation
     */
    
    public WayScript.airbyte_test.models.shared.WebBackendGeographiesListResult webBackendGeographiesListResult;

    public WebBackendListGeographiesResponse withWebBackendGeographiesListResult(WayScript.airbyte_test.models.shared.WebBackendGeographiesListResult webBackendGeographiesListResult) {
        this.webBackendGeographiesListResult = webBackendGeographiesListResult;
        return this;
    }
    
    public WebBackendListGeographiesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
