/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ActorCatalogWithUpdatedAt - A source actor catalog with the timestamp it was mostly recently updated
 */
public class ActorCatalogWithUpdatedAt {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("catalog")
    public java.util.Map<String, Object> catalog;

    public ActorCatalogWithUpdatedAt withCatalog(java.util.Map<String, Object> catalog) {
        this.catalog = catalog;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updatedAt")
    public Long updatedAt;

    public ActorCatalogWithUpdatedAt withUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    public ActorCatalogWithUpdatedAt(){}
}
