/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AdvancedAuth {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authFlowType")
    public AdvancedAuthAuthFlowType authFlowType;

    public AdvancedAuth withAuthFlowType(AdvancedAuthAuthFlowType authFlowType) {
        this.authFlowType = authFlowType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oauthConfigSpecification")
    public OAuthConfigSpecification oauthConfigSpecification;

    public AdvancedAuth withOauthConfigSpecification(OAuthConfigSpecification oauthConfigSpecification) {
        this.oauthConfigSpecification = oauthConfigSpecification;
        return this;
    }
    
    /**
     * Json Path to a field in the connectorSpecification that should exist for the advanced auth to be applicable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("predicateKey")
    public String[] predicateKey;

    public AdvancedAuth withPredicateKey(String[] predicateKey) {
        this.predicateKey = predicateKey;
        return this;
    }
    
    /**
     * Value of the predicate_key fields for the advanced auth to be applicable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("predicateValue")
    public String predicateValue;

    public AdvancedAuth withPredicateValue(String predicateValue) {
        this.predicateValue = predicateValue;
        return this;
    }
    
    public AdvancedAuth(){}
}
