/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AirbyteCatalog - describes the available schema (catalog).
 */
public class AirbyteCatalog {
    @JsonProperty("streams")
    public AirbyteStreamAndConfiguration[] streams;

    public AirbyteCatalog withStreams(AirbyteStreamAndConfiguration[] streams) {
        this.streams = streams;
        return this;
    }
    
    public AirbyteCatalog(@JsonProperty("streams") AirbyteStreamAndConfiguration[] streams) {
        this.streams = streams;
  }
}
