/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AirbyteStreamAndConfiguration - each stream is split in two parts; the immutable schema from source and mutable configuration for destination
 */
public class AirbyteStreamAndConfiguration {
    /**
     * the mutable part of the stream to configure the destination
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("config")
    public AirbyteStreamConfiguration config;

    public AirbyteStreamAndConfiguration withConfig(AirbyteStreamConfiguration config) {
        this.config = config;
        return this;
    }
    
    /**
     * the immutable schema defined by the source
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stream")
    public AirbyteStream stream;

    public AirbyteStreamAndConfiguration withStream(AirbyteStream stream) {
        this.stream = stream;
        return this;
    }
    
    public AirbyteStreamAndConfiguration(){}
}
