/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AttemptSyncConfig {
    /**
     * The values required to configure the destination. The schema for this must match the schema return by destination_definition_specifications/get for the destinationDefinition.
     */
    @JsonProperty("destinationConfiguration")
    public Object destinationConfiguration;

    public AttemptSyncConfig withDestinationConfiguration(Object destinationConfiguration) {
        this.destinationConfiguration = destinationConfiguration;
        return this;
    }
    
    /**
     * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
     */
    @JsonProperty("sourceConfiguration")
    public Object sourceConfiguration;

    public AttemptSyncConfig withSourceConfiguration(Object sourceConfiguration) {
        this.sourceConfiguration = sourceConfiguration;
        return this;
    }
    
    /**
     * Contains the state for a connection. The stateType field identifies what type of state it is. Only the field corresponding to that type will be set, the rest will be null. If stateType=not_set, then none of the fields will be set.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("state")
    public ConnectionState state;

    public AttemptSyncConfig withState(ConnectionState state) {
        this.state = state;
        return this;
    }
    
    public AttemptSyncConfig(@JsonProperty("destinationConfiguration") Object destinationConfiguration, @JsonProperty("sourceConfiguration") Object sourceConfiguration) {
        this.destinationConfiguration = destinationConfiguration;
        this.sourceConfiguration = sourceConfiguration;
  }
}
