/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AttemptFailureType - Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known.
 */
public enum AttemptFailureType {
    CONFIG_ERROR("config_error"),
    SYSTEM_ERROR("system_error"),
    MANUAL_CANCELLATION("manual_cancellation"),
    REFRESH_SCHEMA("refresh_schema");

    @JsonValue
    public final String value;

    private AttemptFailureType(String value) {
        this.value = value;
    }
}
