/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AttemptNormalizationStatusRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("attemptNumber")
    public Integer attemptNumber;

    public AttemptNormalizationStatusRead withAttemptNumber(Integer attemptNumber) {
        this.attemptNumber = attemptNumber;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hasNormalizationFailed")
    public Boolean hasNormalizationFailed;

    public AttemptNormalizationStatusRead withHasNormalizationFailed(Boolean hasNormalizationFailed) {
        this.hasNormalizationFailed = hasNormalizationFailed;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hasRecordsCommitted")
    public Boolean hasRecordsCommitted;

    public AttemptNormalizationStatusRead withHasRecordsCommitted(Boolean hasRecordsCommitted) {
        this.hasRecordsCommitted = hasRecordsCommitted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recordsCommitted")
    public Long recordsCommitted;

    public AttemptNormalizationStatusRead withRecordsCommitted(Long recordsCommitted) {
        this.recordsCommitted = recordsCommitted;
        return this;
    }
    
    public AttemptNormalizationStatusRead(){}
}
