/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AttemptRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bytesSynced")
    public Long bytesSynced;

    public AttemptRead withBytesSynced(Long bytesSynced) {
        this.bytesSynced = bytesSynced;
        return this;
    }
    
    @JsonProperty("createdAt")
    public Long createdAt;

    public AttemptRead withCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("endedAt")
    public Long endedAt;

    public AttemptRead withEndedAt(Long endedAt) {
        this.endedAt = endedAt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("failureSummary")
    public AttemptFailureSummary failureSummary;

    public AttemptRead withFailureSummary(AttemptFailureSummary failureSummary) {
        this.failureSummary = failureSummary;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public AttemptRead withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recordsSynced")
    public Long recordsSynced;

    public AttemptRead withRecordsSynced(Long recordsSynced) {
        this.recordsSynced = recordsSynced;
        return this;
    }
    
    @JsonProperty("status")
    public AttemptStatusEnum status;

    public AttemptRead withStatus(AttemptStatusEnum status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("streamStats")
    public AttemptStreamStats[] streamStats;

    public AttemptRead withStreamStats(AttemptStreamStats[] streamStats) {
        this.streamStats = streamStats;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("totalStats")
    public AttemptStats totalStats;

    public AttemptRead withTotalStats(AttemptStats totalStats) {
        this.totalStats = totalStats;
        return this;
    }
    
    @JsonProperty("updatedAt")
    public Long updatedAt;

    public AttemptRead withUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    public AttemptRead(@JsonProperty("createdAt") Long createdAt, @JsonProperty("id") Long id, @JsonProperty("status") AttemptStatusEnum status, @JsonProperty("updatedAt") Long updatedAt) {
        this.createdAt = createdAt;
        this.id = id;
        this.status = status;
        this.updatedAt = updatedAt;
  }
}
