/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AttemptStats {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bytesEmitted")
    public Long bytesEmitted;

    public AttemptStats withBytesEmitted(Long bytesEmitted) {
        this.bytesEmitted = bytesEmitted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("estimatedBytes")
    public Long estimatedBytes;

    public AttemptStats withEstimatedBytes(Long estimatedBytes) {
        this.estimatedBytes = estimatedBytes;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("estimatedRecords")
    public Long estimatedRecords;

    public AttemptStats withEstimatedRecords(Long estimatedRecords) {
        this.estimatedRecords = estimatedRecords;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recordsCommitted")
    public Long recordsCommitted;

    public AttemptStats withRecordsCommitted(Long recordsCommitted) {
        this.recordsCommitted = recordsCommitted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recordsEmitted")
    public Long recordsEmitted;

    public AttemptStats withRecordsEmitted(Long recordsEmitted) {
        this.recordsEmitted = recordsEmitted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stateMessagesEmitted")
    public Long stateMessagesEmitted;

    public AttemptStats withStateMessagesEmitted(Long stateMessagesEmitted) {
        this.stateMessagesEmitted = stateMessagesEmitted;
        return this;
    }
    
    public AttemptStats(){}
}
