/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AttemptStreamStats {
    @JsonProperty("stats")
    public AttemptStats stats;

    public AttemptStreamStats withStats(AttemptStats stats) {
        this.stats = stats;
        return this;
    }
    
    @JsonProperty("streamName")
    public String streamName;

    public AttemptStreamStats withStreamName(String streamName) {
        this.streamName = streamName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("streamNamespace")
    public String streamNamespace;

    public AttemptStreamStats withStreamNamespace(String streamNamespace) {
        this.streamNamespace = streamNamespace;
        return this;
    }
    
    public AttemptStreamStats(@JsonProperty("stats") AttemptStats stats, @JsonProperty("streamName") String streamName) {
        this.stats = stats;
        this.streamName = streamName;
  }
}
