/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AttemptFailureOrigin - Indicates where the error originated. If not set, the origin of error is not well known.
 */
public enum AttemptFailureOrigin {
    SOURCE("source"),
    DESTINATION("destination"),
    REPLICATION("replication"),
    PERSISTENCE("persistence"),
    NORMALIZATION("normalization"),
    DBT("dbt"),
    AIRBYTE_PLATFORM("airbyte_platform"),
    UNKNOWN("unknown");

    @JsonValue
    public final String value;

    private AttemptFailureOrigin(String value) {
        this.value = value;
    }
}
