/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AttemptStatus {
    RUNNING("running"),
    FAILED("failed"),
    SUCCEEDED("succeeded");

    @JsonValue
    public final String value;

    private AttemptStatus(String value) {
        this.value = value;
    }
}
