/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CatalogDiff - Describes the difference between two Airbyte catalogs.
 */
public class CatalogDiff {
    /**
     * list of stream transformations. order does not matter.
     */
    @JsonProperty("transforms")
    public StreamTransform[] transforms;

    public CatalogDiff withTransforms(StreamTransform[] transforms) {
        this.transforms = transforms;
        return this;
    }
    
    public CatalogDiff(@JsonProperty("transforms") StreamTransform[] transforms) {
        this.transforms = transforms;
  }
}
