/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CheckOperationRead - Successful operation
 */
public class CheckOperationRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public CheckOperationRead withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonProperty("status")
    public CheckOperationReadStatus status;

    public CheckOperationRead withStatus(CheckOperationReadStatus status) {
        this.status = status;
        return this;
    }
    
    public CheckOperationRead(@JsonProperty("status") CheckOperationReadStatus status) {
        this.status = status;
  }
}
