/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CompleteSourceOauthRequest {
    /**
     * The values required to configure OAuth flows. The schema for this must match the `OAuthConfigSpecification.oauthUserInputFromConnectorConfigSpecification` schema.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oAuthInputConfiguration")
    public Object oAuthInputConfiguration;

    public CompleteSourceOauthRequest withOAuthInputConfiguration(Object oAuthInputConfiguration) {
        this.oAuthInputConfiguration = oAuthInputConfiguration;
        return this;
    }
    
    /**
     * The query parameters present in the redirect URL after a user granted consent e.g auth code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("queryParams")
    public java.util.Map<String, Object> queryParams;

    public CompleteSourceOauthRequest withQueryParams(java.util.Map<String, Object> queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    /**
     * When completing OAuth flow to gain an access token, some API sometimes requires to verify that the app re-send the redirectUrl that was used when consent was given.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("redirectUrl")
    public String redirectUrl;

    public CompleteSourceOauthRequest withRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        return this;
    }
    
    @JsonProperty("sourceDefinitionId")
    public String sourceDefinitionId;

    public CompleteSourceOauthRequest withSourceDefinitionId(String sourceDefinitionId) {
        this.sourceDefinitionId = sourceDefinitionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceId")
    public String sourceId;

    public CompleteSourceOauthRequest withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public CompleteSourceOauthRequest withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public CompleteSourceOauthRequest(@JsonProperty("sourceDefinitionId") String sourceDefinitionId, @JsonProperty("workspaceId") String workspaceId) {
        this.sourceDefinitionId = sourceDefinitionId;
        this.workspaceId = workspaceId;
  }
}
