/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CompleteDestinationOAuthRequest {
    @JsonProperty("destinationDefinitionId")
    public String destinationDefinitionId;

    public CompleteDestinationOAuthRequest withDestinationDefinitionId(String destinationDefinitionId) {
        this.destinationDefinitionId = destinationDefinitionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destinationId")
    public String destinationId;

    public CompleteDestinationOAuthRequest withDestinationId(String destinationId) {
        this.destinationId = destinationId;
        return this;
    }
    
    /**
     * The values required to configure OAuth flows. The schema for this must match the `OAuthConfigSpecification.oauthUserInputFromConnectorConfigSpecification` schema.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oAuthInputConfiguration")
    public Object oAuthInputConfiguration;

    public CompleteDestinationOAuthRequest withOAuthInputConfiguration(Object oAuthInputConfiguration) {
        this.oAuthInputConfiguration = oAuthInputConfiguration;
        return this;
    }
    
    /**
     * The query parameters present in the redirect URL after a user granted consent e.g auth code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("queryParams")
    public java.util.Map<String, Object> queryParams;

    public CompleteDestinationOAuthRequest withQueryParams(java.util.Map<String, Object> queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
    /**
     * When completing OAuth flow to gain an access token, some API sometimes requires to verify that the app re-send the redirectUrl that was used when consent was given.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("redirectUrl")
    public String redirectUrl;

    public CompleteDestinationOAuthRequest withRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public CompleteDestinationOAuthRequest withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public CompleteDestinationOAuthRequest(@JsonProperty("destinationDefinitionId") String destinationDefinitionId, @JsonProperty("workspaceId") String workspaceId) {
        this.destinationDefinitionId = destinationDefinitionId;
        this.workspaceId = workspaceId;
  }
}
