/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ConnectionScheduleDataBasicScheduleTimeUnitEnum {
    MINUTES("minutes"),
    HOURS("hours"),
    DAYS("days"),
    WEEKS("weeks"),
    MONTHS("months");

    @JsonValue
    public final String value;

    private ConnectionScheduleDataBasicScheduleTimeUnitEnum(String value) {
        this.value = value;
    }
}
