/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ConnectionStateCreateOrUpdate {
    @JsonProperty("connectionId")
    public String connectionId;

    public ConnectionStateCreateOrUpdate withConnectionId(String connectionId) {
        this.connectionId = connectionId;
        return this;
    }
    
    /**
     * Contains the state for a connection. The stateType field identifies what type of state it is. Only the field corresponding to that type will be set, the rest will be null. If stateType=not_set, then none of the fields will be set.
     */
    @JsonProperty("connectionState")
    public ConnectionState connectionState;

    public ConnectionStateCreateOrUpdate withConnectionState(ConnectionState connectionState) {
        this.connectionState = connectionState;
        return this;
    }
    
    public ConnectionStateCreateOrUpdate(@JsonProperty("connectionId") String connectionId, @JsonProperty("connectionState") ConnectionState connectionState) {
        this.connectionId = connectionId;
        this.connectionState = connectionState;
  }
}
