/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ConnectionScheduleData - schedule for when the the connection should run, per the schedule type
 */
public class ConnectionScheduleData {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("basicSchedule")
    public ConnectionScheduleDataBasicSchedule basicSchedule;

    public ConnectionScheduleData withBasicSchedule(ConnectionScheduleDataBasicSchedule basicSchedule) {
        this.basicSchedule = basicSchedule;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cron")
    public ConnectionScheduleDataCron cron;

    public ConnectionScheduleData withCron(ConnectionScheduleDataCron cron) {
        this.cron = cron;
        return this;
    }
    
    public ConnectionScheduleData(){}
}
