/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConnectionStatusEnum - Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.
 */
public enum ConnectionStatusEnum {
    ACTIVE("active"),
    INACTIVE("inactive"),
    DEPRECATED("deprecated");

    @JsonValue
    public final String value;

    private ConnectionStatusEnum(String value) {
        this.value = value;
    }
}
