/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConnectionScheduleType - determine how the schedule data should be interpreted
 */
public enum ConnectionScheduleType {
    MANUAL("manual"),
    BASIC("basic"),
    CRON("cron");

    @JsonValue
    public final String value;

    private ConnectionScheduleType(String value) {
        this.value = value;
    }
}
