/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ConnectionSchedule - if null, then no schedule is set.
 */
public class ConnectionSchedule {
    @JsonProperty("timeUnit")
    public ConnectionScheduleTimeUnit timeUnit;

    public ConnectionSchedule withTimeUnit(ConnectionScheduleTimeUnit timeUnit) {
        this.timeUnit = timeUnit;
        return this;
    }
    
    @JsonProperty("units")
    public Long units;

    public ConnectionSchedule withUnits(Long units) {
        this.units = units;
        return this;
    }
    
    public ConnectionSchedule(@JsonProperty("timeUnit") ConnectionScheduleTimeUnit timeUnit, @JsonProperty("units") Long units) {
        this.timeUnit = timeUnit;
        this.units = units;
  }
}
