/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ConnectionReadList - Successful operation
 */
public class ConnectionReadList {
    @JsonProperty("connections")
    public ConnectionRead[] connections;

    public ConnectionReadList withConnections(ConnectionRead[] connections) {
        this.connections = connections;
        return this;
    }
    
    public ConnectionReadList(@JsonProperty("connections") ConnectionRead[] connections) {
        this.connections = connections;
  }
}
