/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ConnectionScheduleDataCron {
    @JsonProperty("cronExpression")
    public String cronExpression;

    public ConnectionScheduleDataCron withCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
        return this;
    }
    
    @JsonProperty("cronTimeZone")
    public String cronTimeZone;

    public ConnectionScheduleDataCron withCronTimeZone(String cronTimeZone) {
        this.cronTimeZone = cronTimeZone;
        return this;
    }
    
    public ConnectionScheduleDataCron(@JsonProperty("cronExpression") String cronExpression, @JsonProperty("cronTimeZone") String cronTimeZone) {
        this.cronExpression = cronExpression;
        this.cronTimeZone = cronTimeZone;
  }
}
