/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CustomDestinationDefinitionCreate {
    @JsonProperty("destinationDefinition")
    public DestinationDefinitionCreate destinationDefinition;

    public CustomDestinationDefinitionCreate withDestinationDefinition(DestinationDefinitionCreate destinationDefinition) {
        this.destinationDefinition = destinationDefinition;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public CustomDestinationDefinitionCreate withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public CustomDestinationDefinitionCreate(@JsonProperty("destinationDefinition") DestinationDefinitionCreate destinationDefinition, @JsonProperty("workspaceId") String workspaceId) {
        this.destinationDefinition = destinationDefinition;
        this.workspaceId = workspaceId;
  }
}
