/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DestinationSnippetRead {
    @JsonProperty("destinationDefinitionId")
    public String destinationDefinitionId;

    public DestinationSnippetRead withDestinationDefinitionId(String destinationDefinitionId) {
        this.destinationDefinitionId = destinationDefinitionId;
        return this;
    }
    
    @JsonProperty("destinationId")
    public String destinationId;

    public DestinationSnippetRead withDestinationId(String destinationId) {
        this.destinationId = destinationId;
        return this;
    }
    
    @JsonProperty("destinationName")
    public String destinationName;

    public DestinationSnippetRead withDestinationName(String destinationName) {
        this.destinationName = destinationName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("icon")
    public String icon;

    public DestinationSnippetRead withIcon(String icon) {
        this.icon = icon;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public DestinationSnippetRead withName(String name) {
        this.name = name;
        return this;
    }
    
    public DestinationSnippetRead(@JsonProperty("destinationDefinitionId") String destinationDefinitionId, @JsonProperty("destinationId") String destinationId, @JsonProperty("destinationName") String destinationName, @JsonProperty("name") String name) {
        this.destinationDefinitionId = destinationDefinitionId;
        this.destinationId = destinationId;
        this.destinationName = destinationName;
        this.name = name;
  }
}
