/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DestinationCoreConfig {
    /**
     * The values required to configure the destination. The schema for this must match the schema return by destination_definition_specifications/get for the destinationDefinition.
     */
    @JsonProperty("connectionConfiguration")
    public Object connectionConfiguration;

    public DestinationCoreConfig withConnectionConfiguration(Object connectionConfiguration) {
        this.connectionConfiguration = connectionConfiguration;
        return this;
    }
    
    @JsonProperty("destinationDefinitionId")
    public String destinationDefinitionId;

    public DestinationCoreConfig withDestinationDefinitionId(String destinationDefinitionId) {
        this.destinationDefinitionId = destinationDefinitionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destinationId")
    public String destinationId;

    public DestinationCoreConfig withDestinationId(String destinationId) {
        this.destinationId = destinationId;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public DestinationCoreConfig withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public DestinationCoreConfig(@JsonProperty("connectionConfiguration") Object connectionConfiguration, @JsonProperty("destinationDefinitionId") String destinationDefinitionId, @JsonProperty("workspaceId") String workspaceId) {
        this.connectionConfiguration = connectionConfiguration;
        this.destinationDefinitionId = destinationDefinitionId;
        this.workspaceId = workspaceId;
  }
}
