/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DestinationDefinitionSpecificationRead - Successful operation
 */
public class DestinationDefinitionSpecificationRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("advancedAuth")
    public AdvancedAuth advancedAuth;

    public DestinationDefinitionSpecificationRead withAdvancedAuth(AdvancedAuth advancedAuth) {
        this.advancedAuth = advancedAuth;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authSpecification")
    public DestinationAuthSpecification authSpecification;

    public DestinationDefinitionSpecificationRead withAuthSpecification(DestinationAuthSpecification authSpecification) {
        this.authSpecification = authSpecification;
        return this;
    }
    
    /**
     * The specification for what values are required to configure the destinationDefinition.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connectionSpecification")
    public Object connectionSpecification;

    public DestinationDefinitionSpecificationRead withConnectionSpecification(Object connectionSpecification) {
        this.connectionSpecification = connectionSpecification;
        return this;
    }
    
    @JsonProperty("destinationDefinitionId")
    public String destinationDefinitionId;

    public DestinationDefinitionSpecificationRead withDestinationDefinitionId(String destinationDefinitionId) {
        this.destinationDefinitionId = destinationDefinitionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documentationUrl")
    public String documentationUrl;

    public DestinationDefinitionSpecificationRead withDocumentationUrl(String documentationUrl) {
        this.documentationUrl = documentationUrl;
        return this;
    }
    
    @JsonProperty("jobInfo")
    public SynchronousJobRead jobInfo;

    public DestinationDefinitionSpecificationRead withJobInfo(SynchronousJobRead jobInfo) {
        this.jobInfo = jobInfo;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("supportedDestinationSyncModes")
    public DestinationSyncModeEnum[] supportedDestinationSyncModes;

    public DestinationDefinitionSpecificationRead withSupportedDestinationSyncModes(DestinationSyncModeEnum[] supportedDestinationSyncModes) {
        this.supportedDestinationSyncModes = supportedDestinationSyncModes;
        return this;
    }
    
    public DestinationDefinitionSpecificationRead(@JsonProperty("destinationDefinitionId") String destinationDefinitionId, @JsonProperty("jobInfo") SynchronousJobRead jobInfo) {
        this.destinationDefinitionId = destinationDefinitionId;
        this.jobInfo = jobInfo;
  }
}
