/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum DestinationSyncModeEnum {
    APPEND("append"),
    OVERWRITE("overwrite"),
    APPEND_DEDUP("append_dedup");

    @JsonValue
    public final String value;

    private DestinationSyncModeEnum(String value) {
        this.value = value;
    }
}
