/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DestinationCreate {
    /**
     * The values required to configure the destination. The schema for this must match the schema return by destination_definition_specifications/get for the destinationDefinition.
     */
    @JsonProperty("connectionConfiguration")
    public Object connectionConfiguration;

    public DestinationCreate withConnectionConfiguration(Object connectionConfiguration) {
        this.connectionConfiguration = connectionConfiguration;
        return this;
    }
    
    @JsonProperty("destinationDefinitionId")
    public String destinationDefinitionId;

    public DestinationCreate withDestinationDefinitionId(String destinationDefinitionId) {
        this.destinationDefinitionId = destinationDefinitionId;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public DestinationCreate withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public DestinationCreate withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public DestinationCreate(@JsonProperty("connectionConfiguration") Object connectionConfiguration, @JsonProperty("destinationDefinitionId") String destinationDefinitionId, @JsonProperty("name") String name, @JsonProperty("workspaceId") String workspaceId) {
        this.connectionConfiguration = connectionConfiguration;
        this.destinationDefinitionId = destinationDefinitionId;
        this.name = name;
        this.workspaceId = workspaceId;
  }
}
