/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DestinationCloneConfiguration {
    /**
     * The values required to configure the destination. The schema for this must match the schema return by destination_definition_specifications/get for the destinationDefinition.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connectionConfiguration")
    public Object connectionConfiguration;

    public DestinationCloneConfiguration withConnectionConfiguration(Object connectionConfiguration) {
        this.connectionConfiguration = connectionConfiguration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public DestinationCloneConfiguration withName(String name) {
        this.name = name;
        return this;
    }
    
    public DestinationCloneConfiguration(){}
}
