/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DestinationCloneRequestBody - The values required to configure the destination. The schema for this should have an id of the existing destination along with the configuration you want to change in case.
 */
public class DestinationCloneRequestBody {
    @JsonProperty("destinationCloneId")
    public String destinationCloneId;

    public DestinationCloneRequestBody withDestinationCloneId(String destinationCloneId) {
        this.destinationCloneId = destinationCloneId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destinationConfiguration")
    public DestinationCloneConfiguration destinationConfiguration;

    public DestinationCloneRequestBody withDestinationConfiguration(DestinationCloneConfiguration destinationConfiguration) {
        this.destinationConfiguration = destinationConfiguration;
        return this;
    }
    
    public DestinationCloneRequestBody(@JsonProperty("destinationCloneId") String destinationCloneId) {
        this.destinationCloneId = destinationCloneId;
  }
}
