/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DestinationReadList - Successful operation
 */
public class DestinationReadList {
    @JsonProperty("destinations")
    public DestinationRead[] destinations;

    public DestinationReadList withDestinations(DestinationRead[] destinations) {
        this.destinations = destinations;
        return this;
    }
    
    public DestinationReadList(@JsonProperty("destinations") DestinationRead[] destinations) {
        this.destinations = destinations;
  }
}
