/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DestinationAuthSpecification {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("auth_type")
    public DestinationAuthSpecificationAuthType authType;

    public DestinationAuthSpecification withAuthType(DestinationAuthSpecificationAuthType authType) {
        this.authType = authType;
        return this;
    }
    
    /**
     * An object containing any metadata needed to describe this connector's Oauth flow
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oauth2Specification")
    public OAuth2Specification oauth2Specification;

    public DestinationAuthSpecification withOauth2Specification(OAuth2Specification oauth2Specification) {
        this.oauth2Specification = oauth2Specification;
        return this;
    }
    
    public DestinationAuthSpecification(){}
}
