/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class FieldSchemaUpdate {
    /**
     * JSONSchema representation of the field
     */
    @JsonProperty("newSchema")
    public java.util.Map<String, Object> newSchema;

    public FieldSchemaUpdate withNewSchema(java.util.Map<String, Object> newSchema) {
        this.newSchema = newSchema;
        return this;
    }
    
    /**
     * JSONSchema representation of the field
     */
    @JsonProperty("oldSchema")
    public java.util.Map<String, Object> oldSchema;

    public FieldSchemaUpdate withOldSchema(java.util.Map<String, Object> oldSchema) {
        this.oldSchema = oldSchema;
        return this;
    }
    
    public FieldSchemaUpdate(@JsonProperty("newSchema") java.util.Map<String, Object> newSchema, @JsonProperty("oldSchema") java.util.Map<String, Object> oldSchema) {
        this.newSchema = newSchema;
        this.oldSchema = oldSchema;
  }
}
