/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FieldTransform - Describes the difference between two Streams.
 */
public class FieldTransform {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addField")
    public FieldAdd addField;

    public FieldTransform withAddField(FieldAdd addField) {
        this.addField = addField;
        return this;
    }
    
    @JsonProperty("breaking")
    public Boolean breaking;

    public FieldTransform withBreaking(Boolean breaking) {
        this.breaking = breaking;
        return this;
    }
    
    /**
     * A field name is a list of strings that form the path to the field.
     */
    @JsonProperty("fieldName")
    public String[] fieldName;

    public FieldTransform withFieldName(String[] fieldName) {
        this.fieldName = fieldName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("removeField")
    public FieldRemove removeField;

    public FieldTransform withRemoveField(FieldRemove removeField) {
        this.removeField = removeField;
        return this;
    }
    
    @JsonProperty("transformType")
    public FieldTransformTransformTypeEnum transformType;

    public FieldTransform withTransformType(FieldTransformTransformTypeEnum transformType) {
        this.transformType = transformType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updateFieldSchema")
    public FieldSchemaUpdate updateFieldSchema;

    public FieldTransform withUpdateFieldSchema(FieldSchemaUpdate updateFieldSchema) {
        this.updateFieldSchema = updateFieldSchema;
        return this;
    }
    
    public FieldTransform(@JsonProperty("breaking") Boolean breaking, @JsonProperty("fieldName") String[] fieldName, @JsonProperty("transformType") FieldTransformTransformTypeEnum transformType) {
        this.breaking = breaking;
        this.fieldName = fieldName;
        this.transformType = transformType;
  }
}
