/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class FieldSchemaUpdate {
    /**
     * JSONSchema representation of the field
     */
    @JsonProperty("newSchema")
    public FieldSchema newSchema;

    public FieldSchemaUpdate withNewSchema(FieldSchema newSchema) {
        this.newSchema = newSchema;
        return this;
    }
    
    /**
     * JSONSchema representation of the field
     */
    @JsonProperty("oldSchema")
    public FieldSchema oldSchema;

    public FieldSchemaUpdate withOldSchema(FieldSchema oldSchema) {
        this.oldSchema = oldSchema;
        return this;
    }
    
    public FieldSchemaUpdate(@JsonProperty("newSchema") FieldSchema newSchema, @JsonProperty("oldSchema") FieldSchema oldSchema) {
        this.newSchema = newSchema;
        this.oldSchema = oldSchema;
  }
}
