/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum FieldTransformTransformTypeEnum {
    ADD_FIELD("add_field"),
    REMOVE_FIELD("remove_field"),
    UPDATE_FIELD_SCHEMA("update_field_schema");

    @JsonValue
    public final String value;

    private FieldTransformTransformTypeEnum(String value) {
        this.value = value;
    }
}
