/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class FieldRemove {
    /**
     * JSONSchema representation of the field
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schema")
    public FieldSchema schema;

    public FieldRemove withSchema(FieldSchema schema) {
        this.schema = schema;
        return this;
    }
    
    public FieldRemove(){}
}
