/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;



/**
 * FieldSchema - JSONSchema representation of the field
 */
public class FieldSchema {
    public FieldSchema(){}
}
