/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Geography {
    AUTO("auto"),
    US("us"),
    EU("eu");

    @JsonValue
    public final String value;

    private Geography(String value) {
        this.value = value;
    }
}
