/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GlobalState {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("shared_state")
    public java.util.Map<String, Object> sharedState;

    public GlobalState withSharedState(java.util.Map<String, Object> sharedState) {
        this.sharedState = sharedState;
        return this;
    }
    
    @JsonProperty("streamStates")
    public StreamState[] streamStates;

    public GlobalState withStreamStates(StreamState[] streamStates) {
        this.streamStates = streamStates;
        return this;
    }
    
    public GlobalState(@JsonProperty("streamStates") StreamState[] streamStates) {
        this.streamStates = streamStates;
  }
}
