/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HealthCheckRead - Successful operation
 */
public class HealthCheckRead {
    @JsonProperty("available")
    public Boolean available;

    public HealthCheckRead withAvailable(Boolean available) {
        this.available = available;
        return this;
    }
    
    public HealthCheckRead(@JsonProperty("available") Boolean available) {
        this.available = available;
  }
}
