/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class JobDebugRead {
    @JsonProperty("airbyteVersion")
    public String airbyteVersion;

    public JobDebugRead withAirbyteVersion(String airbyteVersion) {
        this.airbyteVersion = airbyteVersion;
        return this;
    }
    
    @JsonProperty("configId")
    public String configId;

    public JobDebugRead withConfigId(String configId) {
        this.configId = configId;
        return this;
    }
    
    @JsonProperty("configType")
    public JobConfigType configType;

    public JobDebugRead withConfigType(JobConfigType configType) {
        this.configType = configType;
        return this;
    }
    
    @JsonProperty("destinationDefinition")
    public DestinationDefinitionRead destinationDefinition;

    public JobDebugRead withDestinationDefinition(DestinationDefinitionRead destinationDefinition) {
        this.destinationDefinition = destinationDefinition;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public JobDebugRead withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("sourceDefinition")
    public SourceDefinitionRead sourceDefinition;

    public JobDebugRead withSourceDefinition(SourceDefinitionRead sourceDefinition) {
        this.sourceDefinition = sourceDefinition;
        return this;
    }
    
    @JsonProperty("status")
    public JobStatus status;

    public JobDebugRead withStatus(JobStatus status) {
        this.status = status;
        return this;
    }
    
    public JobDebugRead(@JsonProperty("airbyteVersion") String airbyteVersion, @JsonProperty("configId") String configId, @JsonProperty("configType") JobConfigType configType, @JsonProperty("destinationDefinition") DestinationDefinitionRead destinationDefinition, @JsonProperty("id") Long id, @JsonProperty("sourceDefinition") SourceDefinitionRead sourceDefinition, @JsonProperty("status") JobStatus status) {
        this.airbyteVersion = airbyteVersion;
        this.configId = configId;
        this.configType = configType;
        this.destinationDefinition = destinationDefinition;
        this.id = id;
        this.sourceDefinition = sourceDefinition;
        this.status = status;
  }
}
