/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JobInfoLightRead - Successful operation
 */
public class JobInfoLightRead {
    @JsonProperty("job")
    public JobRead job;

    public JobInfoLightRead withJob(JobRead job) {
        this.job = job;
        return this;
    }
    
    public JobInfoLightRead(@JsonProperty("job") JobRead job) {
        this.job = job;
  }
}
