/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * KnownExceptionInfo - Exception occurred; see message for details.
 */
public class KnownExceptionInfo {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("exceptionClassName")
    public String exceptionClassName;

    public KnownExceptionInfo withExceptionClassName(String exceptionClassName) {
        this.exceptionClassName = exceptionClassName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("exceptionStack")
    public String[] exceptionStack;

    public KnownExceptionInfo withExceptionStack(String[] exceptionStack) {
        this.exceptionStack = exceptionStack;
        return this;
    }
    
    @JsonProperty("message")
    public String message;

    public KnownExceptionInfo withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rootCauseExceptionClassName")
    public String rootCauseExceptionClassName;

    public KnownExceptionInfo withRootCauseExceptionClassName(String rootCauseExceptionClassName) {
        this.rootCauseExceptionClassName = rootCauseExceptionClassName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rootCauseExceptionStack")
    public String[] rootCauseExceptionStack;

    public KnownExceptionInfo withRootCauseExceptionStack(String[] rootCauseExceptionStack) {
        this.rootCauseExceptionStack = rootCauseExceptionStack;
        return this;
    }
    
    public KnownExceptionInfo(@JsonProperty("message") String message) {
        this.message = message;
  }
}
