/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class LogRead {
    @JsonProperty("logLines")
    public String[] logLines;

    public LogRead withLogLines(String[] logLines) {
        this.logLines = logLines;
        return this;
    }
    
    public LogRead(@JsonProperty("logLines") String[] logLines) {
        this.logLines = logLines;
  }
}
