/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class LogsRequestBody {
    /**
     * type/source of logs produced
     */
    @JsonProperty("logType")
    public LogType logType;

    public LogsRequestBody withLogType(LogType logType) {
        this.logType = logType;
        return this;
    }
    
    public LogsRequestBody(@JsonProperty("logType") LogType logType) {
        this.logType = logType;
  }
}
