/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LogType - type/source of logs produced
 */
public enum LogType {
    SERVER("server"),
    SCHEDULER("scheduler");

    @JsonValue
    public final String value;

    private LogType(String value) {
        this.value = value;
    }
}
