/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * NamespaceDefinitionTypeEnum - Method used for computing final namespace in destination
 */
public enum NamespaceDefinitionTypeEnum {
    SOURCE("source"),
    DESTINATION("destination"),
    CUSTOMFORMAT("customformat");

    @JsonValue
    public final String value;

    private NamespaceDefinitionTypeEnum(String value) {
        this.value = value;
    }
}
