/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NotFoundKnownExceptionInfo - Object with given id was not found.
 */
public class NotFoundKnownExceptionInfo {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("exceptionClassName")
    public String exceptionClassName;

    public NotFoundKnownExceptionInfo withExceptionClassName(String exceptionClassName) {
        this.exceptionClassName = exceptionClassName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("exceptionStack")
    public String[] exceptionStack;

    public NotFoundKnownExceptionInfo withExceptionStack(String[] exceptionStack) {
        this.exceptionStack = exceptionStack;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public NotFoundKnownExceptionInfo withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("message")
    public String message;

    public NotFoundKnownExceptionInfo withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rootCauseExceptionClassName")
    public String rootCauseExceptionClassName;

    public NotFoundKnownExceptionInfo withRootCauseExceptionClassName(String rootCauseExceptionClassName) {
        this.rootCauseExceptionClassName = rootCauseExceptionClassName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rootCauseExceptionStack")
    public String[] rootCauseExceptionStack;

    public NotFoundKnownExceptionInfo withRootCauseExceptionStack(String[] rootCauseExceptionStack) {
        this.rootCauseExceptionStack = rootCauseExceptionStack;
        return this;
    }
    
    public NotFoundKnownExceptionInfo(@JsonProperty("message") String message) {
        this.message = message;
  }
}
