/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NotificationRead - Successful operation
 */
public class NotificationRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public NotificationRead withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonProperty("status")
    public NotificationReadStatus status;

    public NotificationRead withStatus(NotificationReadStatus status) {
        this.status = status;
        return this;
    }
    
    public NotificationRead(@JsonProperty("status") NotificationReadStatus status) {
        this.status = status;
  }
}
