/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum NotificationReadStatus {
    SUCCEEDED("succeeded"),
    FAILED("failed");

    @JsonValue
    public final String value;

    private NotificationReadStatus(String value) {
        this.value = value;
    }
}
