/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum NotificationType {
    SLACK("slack"),
    CUSTOMERIO("customerio");

    @JsonValue
    public final String value;

    private NotificationType(String value) {
        this.value = value;
    }
}
