/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OperationReadList - Successful operation
 */
public class OperationReadList {
    @JsonProperty("operations")
    public OperationRead[] operations;

    public OperationReadList withOperations(OperationRead[] operations) {
        this.operations = operations;
        return this;
    }
    
    public OperationReadList(@JsonProperty("operations") OperationRead[] operations) {
        this.operations = operations;
  }
}
