/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OperatorTypeEnum {
    NORMALIZATION("normalization"),
    DBT("dbt"),
    WEBHOOK("webhook");

    @JsonValue
    public final String value;

    private OperatorTypeEnum(String value) {
        this.value = value;
    }
}
