/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OperatorNormalizationOptionEnum {
    BASIC("basic");

    @JsonValue
    public final String value;

    private OperatorNormalizationOptionEnum(String value) {
        this.value = value;
    }
}
