/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OperatorWebhookWebhookType {
    DBT_CLOUD("dbtCloud");

    @JsonValue
    public final String value;

    private OperatorWebhookWebhookType(String value) {
        this.value = value;
    }
}
