/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class OperatorWebhookDbtCloud {
    /**
     * The account id associated with the job
     */
    @JsonProperty("accountId")
    public Long accountId;

    public OperatorWebhookDbtCloud withAccountId(Long accountId) {
        this.accountId = accountId;
        return this;
    }
    
    /**
     * The job id associated with the job
     */
    @JsonProperty("jobId")
    public Long jobId;

    public OperatorWebhookDbtCloud withJobId(Long jobId) {
        this.jobId = jobId;
        return this;
    }
    
    public OperatorWebhookDbtCloud(@JsonProperty("accountId") Long accountId, @JsonProperty("jobId") Long jobId) {
        this.accountId = accountId;
        this.jobId = jobId;
  }
}
