/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PrivateSourceDefinitionRead - Successful operation
 */
public class PrivateSourceDefinitionRead {
    @JsonProperty("granted")
    public Boolean granted;

    public PrivateSourceDefinitionRead withGranted(Boolean granted) {
        this.granted = granted;
        return this;
    }
    
    @JsonProperty("sourceDefinition")
    public SourceDefinitionRead sourceDefinition;

    public PrivateSourceDefinitionRead withSourceDefinition(SourceDefinitionRead sourceDefinition) {
        this.sourceDefinition = sourceDefinition;
        return this;
    }
    
    public PrivateSourceDefinitionRead(@JsonProperty("granted") Boolean granted, @JsonProperty("sourceDefinition") SourceDefinitionRead sourceDefinition) {
        this.granted = granted;
        this.sourceDefinition = sourceDefinition;
  }
}
