/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PrivateDestinationDefinitionReadList - Successful operation
 */
public class PrivateDestinationDefinitionReadList {
    @JsonProperty("destinationDefinitions")
    public PrivateDestinationDefinitionRead[] destinationDefinitions;

    public PrivateDestinationDefinitionReadList withDestinationDefinitions(PrivateDestinationDefinitionRead[] destinationDefinitions) {
        this.destinationDefinitions = destinationDefinitions;
        return this;
    }
    
    public PrivateDestinationDefinitionReadList(@JsonProperty("destinationDefinitions") PrivateDestinationDefinitionRead[] destinationDefinitions) {
        this.destinationDefinitions = destinationDefinitions;
  }
}
