/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ReleaseStageEnum {
    ALPHA("alpha"),
    BETA("beta"),
    GENERALLY_AVAILABLE("generally_available"),
    CUSTOM("custom");

    @JsonValue
    public final String value;

    private ReleaseStageEnum(String value) {
        this.value = value;
    }
}
