/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SaveStatsRequestBody {
    @JsonProperty("attemptNumber")
    public Integer attemptNumber;

    public SaveStatsRequestBody withAttemptNumber(Integer attemptNumber) {
        this.attemptNumber = attemptNumber;
        return this;
    }
    
    @JsonProperty("jobId")
    public Long jobId;

    public SaveStatsRequestBody withJobId(Long jobId) {
        this.jobId = jobId;
        return this;
    }
    
    @JsonProperty("stats")
    public AttemptStats stats;

    public SaveStatsRequestBody withStats(AttemptStats stats) {
        this.stats = stats;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("streamStats")
    public AttemptStreamStats[] streamStats;

    public SaveStatsRequestBody withStreamStats(AttemptStreamStats[] streamStats) {
        this.streamStats = streamStats;
        return this;
    }
    
    public SaveStatsRequestBody(@JsonProperty("attemptNumber") Integer attemptNumber, @JsonProperty("jobId") Long jobId, @JsonProperty("stats") AttemptStats stats) {
        this.attemptNumber = attemptNumber;
        this.jobId = jobId;
        this.stats = stats;
  }
}
