/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SaveAttemptSyncConfigRequestBody {
    @JsonProperty("attemptNumber")
    public Integer attemptNumber;

    public SaveAttemptSyncConfigRequestBody withAttemptNumber(Integer attemptNumber) {
        this.attemptNumber = attemptNumber;
        return this;
    }
    
    @JsonProperty("jobId")
    public Long jobId;

    public SaveAttemptSyncConfigRequestBody withJobId(Long jobId) {
        this.jobId = jobId;
        return this;
    }
    
    @JsonProperty("syncConfig")
    public AttemptSyncConfig syncConfig;

    public SaveAttemptSyncConfigRequestBody withSyncConfig(AttemptSyncConfig syncConfig) {
        this.syncConfig = syncConfig;
        return this;
    }
    
    public SaveAttemptSyncConfigRequestBody(@JsonProperty("attemptNumber") Integer attemptNumber, @JsonProperty("jobId") Long jobId, @JsonProperty("syncConfig") AttemptSyncConfig syncConfig) {
        this.attemptNumber = attemptNumber;
        this.jobId = jobId;
        this.syncConfig = syncConfig;
  }
}
