/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SchemaChangeEnum {
    NO_CHANGE("no_change"),
    NON_BREAKING("non_breaking"),
    BREAKING("breaking");

    @JsonValue
    public final String value;

    private SchemaChangeEnum(String value) {
        this.value = value;
    }
}
