/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SetWorkflowInAttemptRequestBody {
    @JsonProperty("attemptNumber")
    public Integer attemptNumber;

    public SetWorkflowInAttemptRequestBody withAttemptNumber(Integer attemptNumber) {
        this.attemptNumber = attemptNumber;
        return this;
    }
    
    @JsonProperty("jobId")
    public Long jobId;

    public SetWorkflowInAttemptRequestBody withJobId(Long jobId) {
        this.jobId = jobId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("processingTaskQueue")
    public String processingTaskQueue;

    public SetWorkflowInAttemptRequestBody withProcessingTaskQueue(String processingTaskQueue) {
        this.processingTaskQueue = processingTaskQueue;
        return this;
    }
    
    @JsonProperty("workflowId")
    public String workflowId;

    public SetWorkflowInAttemptRequestBody withWorkflowId(String workflowId) {
        this.workflowId = workflowId;
        return this;
    }
    
    public SetWorkflowInAttemptRequestBody(@JsonProperty("attemptNumber") Integer attemptNumber, @JsonProperty("jobId") Long jobId, @JsonProperty("workflowId") String workflowId) {
        this.attemptNumber = attemptNumber;
        this.jobId = jobId;
        this.workflowId = workflowId;
  }
}
