/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SlackNotificationConfiguration {
    @JsonProperty("webhook")
    public String webhook;

    public SlackNotificationConfiguration withWebhook(String webhook) {
        this.webhook = webhook;
        return this;
    }
    
    public SlackNotificationConfiguration(@JsonProperty("webhook") String webhook) {
        this.webhook = webhook;
  }
}
