/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SourceCloneConfiguration {
    /**
     * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connectionConfiguration")
    public Object connectionConfiguration;

    public SourceCloneConfiguration withConnectionConfiguration(Object connectionConfiguration) {
        this.connectionConfiguration = connectionConfiguration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public SourceCloneConfiguration withName(String name) {
        this.name = name;
        return this;
    }
    
    public SourceCloneConfiguration(){}
}
