/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;



/**
 * SourceDefinitionSpecification - The specification for what values are required to configure the sourceDefinition.
 */
public class SourceDefinitionSpecification {
    public SourceDefinitionSpecification(){}
}
