/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SourceDefinitionCreate {
    @JsonProperty("dockerImageTag")
    public String dockerImageTag;

    public SourceDefinitionCreate withDockerImageTag(String dockerImageTag) {
        this.dockerImageTag = dockerImageTag;
        return this;
    }
    
    @JsonProperty("dockerRepository")
    public String dockerRepository;

    public SourceDefinitionCreate withDockerRepository(String dockerRepository) {
        this.dockerRepository = dockerRepository;
        return this;
    }
    
    @JsonProperty("documentationUrl")
    public String documentationUrl;

    public SourceDefinitionCreate withDocumentationUrl(String documentationUrl) {
        this.documentationUrl = documentationUrl;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("icon")
    public String icon;

    public SourceDefinitionCreate withIcon(String icon) {
        this.icon = icon;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public SourceDefinitionCreate withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * actor definition specific resource requirements. if default is set, these are the requirements that should be set for ALL jobs run for this actor definition. it is overriden by the job type specific configurations. if not set, the platform will use defaults. these values will be overriden by configuration at the connection level.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resourceRequirements")
    public ActorDefinitionResourceRequirements resourceRequirements;

    public SourceDefinitionCreate withResourceRequirements(ActorDefinitionResourceRequirements resourceRequirements) {
        this.resourceRequirements = resourceRequirements;
        return this;
    }
    
    public SourceDefinitionCreate(@JsonProperty("dockerImageTag") String dockerImageTag, @JsonProperty("dockerRepository") String dockerRepository, @JsonProperty("documentationUrl") String documentationUrl, @JsonProperty("name") String name) {
        this.dockerImageTag = dockerImageTag;
        this.dockerRepository = dockerRepository;
        this.documentationUrl = documentationUrl;
        this.name = name;
  }
}
