/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SourceDiscoverSchemaRequestBody {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connectionId")
    public String connectionId;

    public SourceDiscoverSchemaRequestBody withConnectionId(String connectionId) {
        this.connectionId = connectionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("disable_cache")
    public Boolean disableCache;

    public SourceDiscoverSchemaRequestBody withDisableCache(Boolean disableCache) {
        this.disableCache = disableCache;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notifySchemaChange")
    public Boolean notifySchemaChange;

    public SourceDiscoverSchemaRequestBody withNotifySchemaChange(Boolean notifySchemaChange) {
        this.notifySchemaChange = notifySchemaChange;
        return this;
    }
    
    @JsonProperty("sourceId")
    public String sourceId;

    public SourceDiscoverSchemaRequestBody withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    public SourceDiscoverSchemaRequestBody(@JsonProperty("sourceId") String sourceId) {
        this.sourceId = sourceId;
  }
}
