/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceDiscoverSchemaWriteRequestBody - to write this requested object to database.
 */
public class SourceDiscoverSchemaWriteRequestBody {
    /**
     * describes the available schema (catalog).
     */
    @JsonProperty("catalog")
    public AirbyteCatalog catalog;

    public SourceDiscoverSchemaWriteRequestBody withCatalog(AirbyteCatalog catalog) {
        this.catalog = catalog;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("configurationHash")
    public String configurationHash;

    public SourceDiscoverSchemaWriteRequestBody withConfigurationHash(String configurationHash) {
        this.configurationHash = configurationHash;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connectorVersion")
    public String connectorVersion;

    public SourceDiscoverSchemaWriteRequestBody withConnectorVersion(String connectorVersion) {
        this.connectorVersion = connectorVersion;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceId")
    public String sourceId;

    public SourceDiscoverSchemaWriteRequestBody withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    public SourceDiscoverSchemaWriteRequestBody(@JsonProperty("catalog") AirbyteCatalog catalog) {
        this.catalog = catalog;
  }
}
