/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceCloneRequestBody - The values required to configure the source. The schema for this should have an id of the existing source along with the configuration you want to change in case.
 */
public class SourceCloneRequestBody {
    @JsonProperty("sourceCloneId")
    public String sourceCloneId;

    public SourceCloneRequestBody withSourceCloneId(String sourceCloneId) {
        this.sourceCloneId = sourceCloneId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceConfiguration")
    public SourceCloneConfiguration sourceConfiguration;

    public SourceCloneRequestBody withSourceConfiguration(SourceCloneConfiguration sourceConfiguration) {
        this.sourceConfiguration = sourceConfiguration;
        return this;
    }
    
    public SourceCloneRequestBody(@JsonProperty("sourceCloneId") String sourceCloneId) {
        this.sourceCloneId = sourceCloneId;
  }
}
