/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceDefinitionReadSourceTypeEnum {
    API("api"),
    FILE("file"),
    DATABASE("database"),
    CUSTOM("custom");

    @JsonValue
    public final String value;

    private SourceDefinitionReadSourceTypeEnum(String value) {
        this.value = value;
    }
}
