/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SourceCreate {
    /**
     * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
     */
    @JsonProperty("connectionConfiguration")
    public Object connectionConfiguration;

    public SourceCreate withConnectionConfiguration(Object connectionConfiguration) {
        this.connectionConfiguration = connectionConfiguration;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public SourceCreate withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("sourceDefinitionId")
    public String sourceDefinitionId;

    public SourceCreate withSourceDefinitionId(String sourceDefinitionId) {
        this.sourceDefinitionId = sourceDefinitionId;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public SourceCreate withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public SourceCreate(@JsonProperty("connectionConfiguration") Object connectionConfiguration, @JsonProperty("name") String name, @JsonProperty("sourceDefinitionId") String sourceDefinitionId, @JsonProperty("workspaceId") String workspaceId) {
        this.connectionConfiguration = connectionConfiguration;
        this.name = name;
        this.sourceDefinitionId = sourceDefinitionId;
        this.workspaceId = workspaceId;
  }
}
