/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SourceOauthConsentRequest {
    /**
     * The values required to configure OAuth flows. The schema for this must match the `OAuthConfigSpecification.oauthUserInputFromConnectorConfigSpecification` schema.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oAuthInputConfiguration")
    public Object oAuthInputConfiguration;

    public SourceOauthConsentRequest withOAuthInputConfiguration(Object oAuthInputConfiguration) {
        this.oAuthInputConfiguration = oAuthInputConfiguration;
        return this;
    }
    
    /**
     * The url to redirect to after getting the user consent
     */
    @JsonProperty("redirectUrl")
    public String redirectUrl;

    public SourceOauthConsentRequest withRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        return this;
    }
    
    @JsonProperty("sourceDefinitionId")
    public String sourceDefinitionId;

    public SourceOauthConsentRequest withSourceDefinitionId(String sourceDefinitionId) {
        this.sourceDefinitionId = sourceDefinitionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceId")
    public String sourceId;

    public SourceOauthConsentRequest withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public SourceOauthConsentRequest withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public SourceOauthConsentRequest(@JsonProperty("redirectUrl") String redirectUrl, @JsonProperty("sourceDefinitionId") String sourceDefinitionId, @JsonProperty("workspaceId") String workspaceId) {
        this.redirectUrl = redirectUrl;
        this.sourceDefinitionId = sourceDefinitionId;
        this.workspaceId = workspaceId;
  }
}
