/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceRead - Successful operation
 */
public class SourceRead {
    /**
     * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
     */
    @JsonProperty("connectionConfiguration")
    public Object connectionConfiguration;

    public SourceRead withConnectionConfiguration(Object connectionConfiguration) {
        this.connectionConfiguration = connectionConfiguration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("icon")
    public String icon;

    public SourceRead withIcon(String icon) {
        this.icon = icon;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public SourceRead withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("sourceDefinitionId")
    public String sourceDefinitionId;

    public SourceRead withSourceDefinitionId(String sourceDefinitionId) {
        this.sourceDefinitionId = sourceDefinitionId;
        return this;
    }
    
    @JsonProperty("sourceId")
    public String sourceId;

    public SourceRead withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    @JsonProperty("sourceName")
    public String sourceName;

    public SourceRead withSourceName(String sourceName) {
        this.sourceName = sourceName;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public SourceRead withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public SourceRead(@JsonProperty("connectionConfiguration") Object connectionConfiguration, @JsonProperty("name") String name, @JsonProperty("sourceDefinitionId") String sourceDefinitionId, @JsonProperty("sourceId") String sourceId, @JsonProperty("sourceName") String sourceName, @JsonProperty("workspaceId") String workspaceId) {
        this.connectionConfiguration = connectionConfiguration;
        this.name = name;
        this.sourceDefinitionId = sourceDefinitionId;
        this.sourceId = sourceId;
        this.sourceName = sourceName;
        this.workspaceId = workspaceId;
  }
}
