/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SourceIdRequestBody {
    @JsonProperty("sourceId")
    public String sourceId;

    public SourceIdRequestBody withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    public SourceIdRequestBody(@JsonProperty("sourceId") String sourceId) {
        this.sourceId = sourceId;
  }
}
