/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceReadList - Successful operation
 */
public class SourceReadList {
    @JsonProperty("sources")
    public SourceRead[] sources;

    public SourceReadList withSources(SourceRead[] sources) {
        this.sources = sources;
        return this;
    }
    
    public SourceReadList(@JsonProperty("sources") SourceRead[] sources) {
        this.sources = sources;
  }
}
