/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceDefinitionSpecificationRead - Successful operation
 */
public class SourceDefinitionSpecificationRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("advancedAuth")
    public AdvancedAuth advancedAuth;

    public SourceDefinitionSpecificationRead withAdvancedAuth(AdvancedAuth advancedAuth) {
        this.advancedAuth = advancedAuth;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authSpecification")
    public SourceAuthSpecification authSpecification;

    public SourceDefinitionSpecificationRead withAuthSpecification(SourceAuthSpecification authSpecification) {
        this.authSpecification = authSpecification;
        return this;
    }
    
    /**
     * The specification for what values are required to configure the sourceDefinition.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connectionSpecification")
    public java.util.Map<String, Object> connectionSpecification;

    public SourceDefinitionSpecificationRead withConnectionSpecification(java.util.Map<String, Object> connectionSpecification) {
        this.connectionSpecification = connectionSpecification;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documentationUrl")
    public String documentationUrl;

    public SourceDefinitionSpecificationRead withDocumentationUrl(String documentationUrl) {
        this.documentationUrl = documentationUrl;
        return this;
    }
    
    @JsonProperty("jobInfo")
    public SynchronousJobRead jobInfo;

    public SourceDefinitionSpecificationRead withJobInfo(SynchronousJobRead jobInfo) {
        this.jobInfo = jobInfo;
        return this;
    }
    
    @JsonProperty("sourceDefinitionId")
    public String sourceDefinitionId;

    public SourceDefinitionSpecificationRead withSourceDefinitionId(String sourceDefinitionId) {
        this.sourceDefinitionId = sourceDefinitionId;
        return this;
    }
    
    public SourceDefinitionSpecificationRead(@JsonProperty("jobInfo") SynchronousJobRead jobInfo, @JsonProperty("sourceDefinitionId") String sourceDefinitionId) {
        this.jobInfo = jobInfo;
        this.sourceDefinitionId = sourceDefinitionId;
  }
}
