/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class StreamTransform {
    @JsonProperty("streamDescriptor")
    public StreamDescriptor streamDescriptor;

    public StreamTransform withStreamDescriptor(StreamDescriptor streamDescriptor) {
        this.streamDescriptor = streamDescriptor;
        return this;
    }
    
    @JsonProperty("transformType")
    public StreamTransformTransformTypeEnum transformType;

    public StreamTransform withTransformType(StreamTransformTransformTypeEnum transformType) {
        this.transformType = transformType;
        return this;
    }
    
    /**
     * list of field transformations. order does not matter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updateStream")
    public FieldTransform[] updateStream;

    public StreamTransform withUpdateStream(FieldTransform[] updateStream) {
        this.updateStream = updateStream;
        return this;
    }
    
    public StreamTransform(@JsonProperty("streamDescriptor") StreamDescriptor streamDescriptor, @JsonProperty("transformType") StreamTransformTransformTypeEnum transformType) {
        this.streamDescriptor = streamDescriptor;
        this.transformType = transformType;
  }
}
