/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class WebBackendConnectionRequestBody {
    @JsonProperty("connectionId")
    public String connectionId;

    public WebBackendConnectionRequestBody withConnectionId(String connectionId) {
        this.connectionId = connectionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("withRefreshedCatalog")
    public Boolean withRefreshedCatalog;

    public WebBackendConnectionRequestBody withWithRefreshedCatalog(Boolean withRefreshedCatalog) {
        this.withRefreshedCatalog = withRefreshedCatalog;
        return this;
    }
    
    public WebBackendConnectionRequestBody(@JsonProperty("connectionId") String connectionId) {
        this.connectionId = connectionId;
  }
}
