/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WebBackendGeographiesListResult - Successful operation
 */
public class WebBackendGeographiesListResult {
    @JsonProperty("geographies")
    public Geography[] geographies;

    public WebBackendGeographiesListResult withGeographies(Geography[] geographies) {
        this.geographies = geographies;
        return this;
    }
    
    public WebBackendGeographiesListResult(@JsonProperty("geographies") Geography[] geographies) {
        this.geographies = geographies;
  }
}
