/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class WebBackendConnectionCreate {
    @JsonProperty("destinationId")
    public String destinationId;

    public WebBackendConnectionCreate withDestinationId(String destinationId) {
        this.destinationId = destinationId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("geography")
    public GeographyEnum geography;

    public WebBackendConnectionCreate withGeography(GeographyEnum geography) {
        this.geography = geography;
        return this;
    }
    
    /**
     * Optional name of the connection
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public WebBackendConnectionCreate withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Method used for computing final namespace in destination
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("namespaceDefinition")
    public NamespaceDefinitionTypeEnum namespaceDefinition;

    public WebBackendConnectionCreate withNamespaceDefinition(NamespaceDefinitionTypeEnum namespaceDefinition) {
        this.namespaceDefinition = namespaceDefinition;
        return this;
    }
    
    /**
     * Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If "${SOURCE_NAMESPACE}" then behaves like namespaceDefinition = 'source'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("namespaceFormat")
    public String namespaceFormat;

    public WebBackendConnectionCreate withNamespaceFormat(String namespaceFormat) {
        this.namespaceFormat = namespaceFormat;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nonBreakingChangesPreference")
    public NonBreakingChangesPreferenceEnum nonBreakingChangesPreference;

    public WebBackendConnectionCreate withNonBreakingChangesPreference(NonBreakingChangesPreferenceEnum nonBreakingChangesPreference) {
        this.nonBreakingChangesPreference = nonBreakingChangesPreference;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("operationIds")
    public String[] operationIds;

    public WebBackendConnectionCreate withOperationIds(String[] operationIds) {
        this.operationIds = operationIds;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("operations")
    public OperationCreate[] operations;

    public WebBackendConnectionCreate withOperations(OperationCreate[] operations) {
        this.operations = operations;
        return this;
    }
    
    /**
     * Prefix that will be prepended to the name of each stream when it is written to the destination.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prefix")
    public String prefix;

    public WebBackendConnectionCreate withPrefix(String prefix) {
        this.prefix = prefix;
        return this;
    }
    
    /**
     * optional resource requirements to run workers (blank for unbounded allocations)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resourceRequirements")
    public ResourceRequirements resourceRequirements;

    public WebBackendConnectionCreate withResourceRequirements(ResourceRequirements resourceRequirements) {
        this.resourceRequirements = resourceRequirements;
        return this;
    }
    
    /**
     * if null, then no schedule is set.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schedule")
    public ConnectionSchedule schedule;

    public WebBackendConnectionCreate withSchedule(ConnectionSchedule schedule) {
        this.schedule = schedule;
        return this;
    }
    
    /**
     * schedule for when the the connection should run, per the schedule type
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scheduleData")
    public ConnectionScheduleData scheduleData;

    public WebBackendConnectionCreate withScheduleData(ConnectionScheduleData scheduleData) {
        this.scheduleData = scheduleData;
        return this;
    }
    
    /**
     * determine how the schedule data should be interpreted
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scheduleType")
    public ConnectionScheduleTypeEnum scheduleType;

    public WebBackendConnectionCreate withScheduleType(ConnectionScheduleTypeEnum scheduleType) {
        this.scheduleType = scheduleType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceCatalogId")
    public String sourceCatalogId;

    public WebBackendConnectionCreate withSourceCatalogId(String sourceCatalogId) {
        this.sourceCatalogId = sourceCatalogId;
        return this;
    }
    
    @JsonProperty("sourceId")
    public String sourceId;

    public WebBackendConnectionCreate withSourceId(String sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    /**
     * Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.
     */
    @JsonProperty("status")
    public ConnectionStatusEnum status;

    public WebBackendConnectionCreate withStatus(ConnectionStatusEnum status) {
        this.status = status;
        return this;
    }
    
    /**
     * describes the available schema (catalog).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("syncCatalog")
    public AirbyteCatalog syncCatalog;

    public WebBackendConnectionCreate withSyncCatalog(AirbyteCatalog syncCatalog) {
        this.syncCatalog = syncCatalog;
        return this;
    }
    
    public WebBackendConnectionCreate(@JsonProperty("destinationId") String destinationId, @JsonProperty("sourceId") String sourceId, @JsonProperty("status") ConnectionStatusEnum status) {
        this.destinationId = destinationId;
        this.sourceId = sourceId;
        this.status = status;
  }
}
