/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class WebBackendWorkspaceState {
    @JsonProperty("workspaceId")
    public String workspaceId;

    public WebBackendWorkspaceState withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public WebBackendWorkspaceState(@JsonProperty("workspaceId") String workspaceId) {
        this.workspaceId = workspaceId;
  }
}
