/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class WebBackendConnectionListRequestBody {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destinationId")
    public String[] destinationId;

    public WebBackendConnectionListRequestBody withDestinationId(String[] destinationId) {
        this.destinationId = destinationId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sourceId")
    public String[] sourceId;

    public WebBackendConnectionListRequestBody withSourceId(String[] sourceId) {
        this.sourceId = sourceId;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public WebBackendConnectionListRequestBody withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public WebBackendConnectionListRequestBody(@JsonProperty("workspaceId") String workspaceId) {
        this.workspaceId = workspaceId;
  }
}
