/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class WebBackendOperationCreateOrUpdate {
    @JsonProperty("name")
    public String name;

    public WebBackendOperationCreateOrUpdate withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("operationId")
    public String operationId;

    public WebBackendOperationCreateOrUpdate withOperationId(String operationId) {
        this.operationId = operationId;
        return this;
    }
    
    @JsonProperty("operatorConfiguration")
    public OperatorConfiguration operatorConfiguration;

    public WebBackendOperationCreateOrUpdate withOperatorConfiguration(OperatorConfiguration operatorConfiguration) {
        this.operatorConfiguration = operatorConfiguration;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public WebBackendOperationCreateOrUpdate withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public WebBackendOperationCreateOrUpdate(@JsonProperty("name") String name, @JsonProperty("operatorConfiguration") OperatorConfiguration operatorConfiguration, @JsonProperty("workspaceId") String workspaceId) {
        this.name = name;
        this.operatorConfiguration = operatorConfiguration;
        this.workspaceId = workspaceId;
  }
}
