/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WebBackendCheckUpdatesRead - Summary of source and destination definitions that could be updated
 */
public class WebBackendCheckUpdatesRead {
    @JsonProperty("destinationDefinitions")
    public Long destinationDefinitions;

    public WebBackendCheckUpdatesRead withDestinationDefinitions(Long destinationDefinitions) {
        this.destinationDefinitions = destinationDefinitions;
        return this;
    }
    
    @JsonProperty("sourceDefinitions")
    public Long sourceDefinitions;

    public WebBackendCheckUpdatesRead withSourceDefinitions(Long sourceDefinitions) {
        this.sourceDefinitions = sourceDefinitions;
        return this;
    }
    
    public WebBackendCheckUpdatesRead(@JsonProperty("destinationDefinitions") Long destinationDefinitions, @JsonProperty("sourceDefinitions") Long sourceDefinitions) {
        this.destinationDefinitions = destinationDefinitions;
        this.sourceDefinitions = sourceDefinitions;
  }
}
