/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class WebhookConfigWrite {
    /**
     * an auth token, to be passed as the value for an HTTP Authorization header.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authToken")
    public String authToken;

    public WebhookConfigWrite withAuthToken(String authToken) {
        this.authToken = authToken;
        return this;
    }
    
    /**
     * human readable name for this webhook e.g. for UI display.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public WebhookConfigWrite withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * if supplied, the webhook config will be validated by checking that this URL returns a 2xx response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validationUrl")
    public String validationUrl;

    public WebhookConfigWrite withValidationUrl(String validationUrl) {
        this.validationUrl = validationUrl;
        return this;
    }
    
    public WebhookConfigWrite(){}
}
