/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class WorkflowStateRead {
    @JsonProperty("running")
    public Boolean running;

    public WorkflowStateRead withRunning(Boolean running) {
        this.running = running;
        return this;
    }
    
    public WorkflowStateRead(@JsonProperty("running") Boolean running) {
        this.running = running;
  }
}
