/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class WorkspaceCreate {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("anonymousDataCollection")
    public Boolean anonymousDataCollection;

    public WorkspaceCreate withAnonymousDataCollection(Boolean anonymousDataCollection) {
        this.anonymousDataCollection = anonymousDataCollection;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("defaultGeography")
    public Geography defaultGeography;

    public WorkspaceCreate withDefaultGeography(Geography defaultGeography) {
        this.defaultGeography = defaultGeography;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("displaySetupWizard")
    public Boolean displaySetupWizard;

    public WorkspaceCreate withDisplaySetupWizard(Boolean displaySetupWizard) {
        this.displaySetupWizard = displaySetupWizard;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public WorkspaceCreate withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public WorkspaceCreate withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("news")
    public Boolean news;

    public WorkspaceCreate withNews(Boolean news) {
        this.news = news;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notifications")
    public Notification[] notifications;

    public WorkspaceCreate withNotifications(Notification[] notifications) {
        this.notifications = notifications;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("securityUpdates")
    public Boolean securityUpdates;

    public WorkspaceCreate withSecurityUpdates(Boolean securityUpdates) {
        this.securityUpdates = securityUpdates;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("webhookConfigs")
    public WebhookConfigWrite[] webhookConfigs;

    public WorkspaceCreate withWebhookConfigs(WebhookConfigWrite[] webhookConfigs) {
        this.webhookConfigs = webhookConfigs;
        return this;
    }
    
    public WorkspaceCreate(@JsonProperty("name") String name) {
        this.name = name;
  }
}
