/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package WayScript.airbyte_test.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WorkspaceReadList - Successful operation
 */
public class WorkspaceReadList {
    @JsonProperty("workspaces")
    public WorkspaceRead[] workspaces;

    public WorkspaceReadList withWorkspaces(WorkspaceRead[] workspaces) {
        this.workspaces = workspaces;
        return this;
    }
    
    public WorkspaceReadList(@JsonProperty("workspaces") WorkspaceRead[] workspaces) {
        this.workspaces = workspaces;
  }
}
